### ISSUE TITLE
Chrome no longer displays any pages with Wizmage enabled

### ISSUE THREAD

**Issue by hadamardgeometry** [elicym/wizmage#15]
First of all, thank you for making Wizmage.  It's by far the best extension I've ever used.  I consider it indispensable.

Today, Chrome stopped displaying _any_ page content.  Disabling Wizmage fixes this.  But reenabling Wizmage causes each page to simply be a blank screen.

I get this behavior even if Wizmage is on Pause.  Only disabling Wizmage solves this.

![image](https://github.com/ecymerman/wizmage/assets/162063765/4ca0b405-09bc-4613-8375-74b93794d734)

Interestingly, the HTML of the page is loaded, as I can do View Source or Inspect.  But the display is a blank white screen.

I see on [the extension home page](https://chromewebstore.google.com/detail/ifoggbfaoakkojipahnplnbfnhhhnmlp) that there was a new update today.  Perhaps that is the culprit?

I'll add that I'm running Chrome 109 (for specific reasons, I need to use that version).

**Comment by hadamardgeometry** [comment]
I had a similar experience on a different computer.  Everything ran great, until, even while Chrome was still running, the extension updated.  Then pure white pages, even with the extension on pause - only disabling it fixed it.

**Comment by akraines** [comment]
White screen normally means a javascript error

**Comment by hadamardgeometry** [comment]
Chrome Dev Tools doesn't stop in JS debugger.
Also - disabling Wizmage causes the page to render, even without doing a reload.

**Comment by ecymerman** [comment]
An update was done last week to switch from Manifest V2 to Manifest V3, since the former won't be allowed for much longer.
In order to migrate the settings, from localStorage using in V2 to chrome.storage used in V3, I used an offscreen document.
Offscreen documents are only properly supported from Chrome 113 onwards. Users of Chrome 109 (which is the latest version supported by Windows 7) will have found that Wizmage no longer works.
To combat this, I disabled migration when offscreen documents are not available, in version 3.1.4. So you should find that Wizmage now works, just you will have to re-input your settings.

**Comment by hadamardgeometry** [comment]
Super! Seems to work now! I'll report back if I find any other issues.

For my own knowledge, is this understanding correct:
1. To move to Manifest V3, you moved from storing config in `localStorage` to `chrome.storage`
2. To copy the config, you used an offscreen document. _(This is a one time usage: use the offscreen document to copy the settings once - it's not part of the actual runtime behavior)_
4. Which is not supported < Chrome 113
5. Which caused rendering to freeze

Solution: If offscreen document isn't available (or perhaps if any exception is thrown?), don't migrate the settings.  Problem solved.

Is that correct? One question: Why use an offscreen document to migrate the settings and not just plain Javascript?

Thank you again for this amazing extension.

**Comment by ecymerman** [comment]
That is all correct.
Regarding your question about localStorage, read [this discussion](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/T3_8r6Anv14/m/t5TKaYkbAgAJ).
